# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=7000']
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["-t", "py39", "-l", "88"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--ignore=W503,E203,E241,E221,E251,E704",
               "--extend-immutable-calls=settings"]
        additional_dependencies: ["flake8-bugbear"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-ll", "-c", "pyproject.toml"]
        files: .py$
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["-l", "88", "--lbt", "1"]
  - repo: https://github.com/PyCQA/doc8/
    rev: v1.1.1
    hooks:
      - id: doc8
        args: ["--config", "setup.cfg"]
        require_serial: false
        files: .rst$
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: tests
        args: ["--add-ignore=D107,D105,D301"]
        additional_dependencies: [toml]
